github.com:
    users:
        kingemhyr:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kingemhyr
